title: TENSOR Framework Documentation
description: Official docs & interactive visualizer for the TENSOR standard
theme: minima
plugins:
  - jekyll-feed

# Include the core JSON and visualizer folders as static files
include:
  - core
  - visualizer

# Tell Jekyll “my site lives at /<repo-name>”
baseurl: "/tensor-framework"
url:    "https://tensor-standards-consortium.github.io"