title: TENSOR Framework Documentation
description: Official docs & interactive visualizer for the TENSOR standard
theme: minima
plugins:
  - jekyll-feed

# GitHub Pages settings
baseurl: "/tensor-standards-consortium"
url:    "https://tensor-standards-consortium.github.io"

# Include these so Jekyll will bundle them
include:
  - core
  - visualizer
  - schemas
