title: TENSOR Framework Documentation
description: Official docs & interactive visualizer for the TENSOR standard
theme: minima
plugins:
  - jekyll-feed

# YOUR REPO NAME here:
baseurl: "/tensor-framework"
url:    "https://tensor-standards-consortium.github.io"

include:
  - core
  - visualizer
  - schemas
