# .github/workflows/gh-pages.yml
name: Deploy TENSOR Framework Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages:   write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      - name: Install Jekyll & theme
        run: gem install jekyll minima jekyll-feed

      - name: Prepare docs source
        run: |
          # Clean out any old copies
          rm -rf docs/core docs/visualizer docs/assets/images

          # Copy versioned core JSONs & manifest
          cp -R core docs/core
          cp core/manifest.json docs/_data/manifest.json

          # Copy visualizer app
          cp -R visualizer docs/visualizer

          # Copy your logos into the docs assets/images
          mkdir -p docs/assets/images
          cp assets/images/logo-framework.png docs/assets/images/
          cp assets/images/logo-consortium.png docs/assets/images/

      - name: Build Jekyll site
        run: jekyll build --source docs --destination public

      - name: Promote core versions & create “latest” symlink
        run: |
          mkdir -p public/core
          cp public/_data/manifest.json public/core/manifest.json
          latest=$(jq -r .latest public/core/manifest.json)
          mkdir -p public/core/${latest}
          cp public/core/${latest}/tensor-core.json public/core/${latest}/
          cd public/core && ln -sfn ${latest} latest

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Publish
        uses: actions/deploy-pages@v4
