# .github/workflows/pages.yml
name: Deploy Tensor Framework Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Build your Tailwind CSS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend deps & build CSS
        working-directory: docs
        run: |
          npm ci
          npm run build:css

      # 2) Install Ruby & Jekyll plugins
      - name: Setup Ruby & Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.4"

      - name: Install Jekyll & theme
        run: |
          gem install jekyll minima jekyll-feed

      # 3) Build the static site
      - name: Build Jekyll site
        run: |
          jekyll build --source docs --destination public

      # 4) Deploy the generated `public/`
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
