name: Deploy TENSOR Framework Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages:   write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.4'

      - name: Install Jekyll & Plugins
        run: gem install jekyll minima jekyll-feed

      - name: Build Jekyll site
        run: jekyll build --source docs --destination public

      - name: Copy Visualizer
        run: cp -R visualizer public/visualizer

      - name: Copy core JSON versions & create “latest” symlink
        run: |
          mkdir -p public/core
          cp core/manifest.json public/core/
          latest=$(jq -r .latest core/manifest.json)
          mkdir -p public/core/${latest}
          cp core/${latest}/tensor-core.json public/core/${latest}/
          cd public/core && ln -sfn ${latest} latest

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Publish
        uses: actions/deploy-pages@v4
